get:
  tags:
    - home
  summary: Get forum settings
  description: This route retrieves forum settings and user-specific settings for client-side options on the forum.
  responses:
    "200":
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              relative_path:
                type: string
              upload_url:
                type: string
              assetBaseUrl:
                type: string
              asset_base_url:
                type: string
              siteTitle:
                type: string
              browserTitle:
                type: string
              titleLayout:
                type: string
              showSiteTitle:
                type: boolean
              maintenanceMode:
                type: boolean
              postQueue:
                type: number
              minimumTitleLength:
                type: number
              maximumTitleLength:
                type: number
              minimumPostLength:
                type: number
              maximumPostLength:
                type: number
              minimumTagsPerTopic:
                type: number
              maximumTagsPerTopic:
                type: number
              minimumTagLength:
                type: number
              undoTimeout:
                type: number
              maximumTagLength:
                type: number
              useOutgoingLinksPage:
                type: boolean
              allowGuestHandles:
                type: boolean
              allowTopicsThumbnail:
                type: boolean
              usePagination:
                type: boolean
              disableChat:
                type: boolean
              disableChatMessageEditing:
                type: boolean
              maximumChatMessageLength:
                type: number
              socketioTransports:
                type: array
                items:
                  type: string
              socketioOrigins:
                type: string
              websocketAddress:
                type: string
              maxReconnectionAttempts:
                type: number
              reconnectionDelay:
                type: number
              topicsPerPage:
                type: number
              postsPerPage:
                type: number
              maximumFileSize:
                type: number
              theme:id:
                type: string
              theme:src:
                type: string
              defaultLang:
                type: string
              userLang:
                type: string
              loggedIn:
                type: boolean
              uid:
                type: number
                description: A user identifier
              cache-buster:
                type: string
              topicPostSort:
                type: string
              categoryTopicSort:
                type: string
              csrf_token:
                type: string
              searchEnabled:
                type: boolean
              searchDefaultInQuick:
                type: string
              disableCustomUserSkins:
                type: boolean
              bootswatchSkin:
                type: string
              defaultBootswatchSkin:
                type: string
              composer:showHelpTab:
                type: boolean
              enablePostHistory:
                type: boolean
              timeagoCutoff:
                type: number
              timeagoCodes:
                type: array
                items:
                  type: string
              cookies:
                type: object
                properties:
                  enabled:
                    type: boolean
                  message:
                    type: string
                  dismiss:
                    type: string
                  link:
                    type: string
                  link_url:
                    type: string
              thumbs:
                type: object
                properties:
                  size:
                    type: number
              acpLang:
                type: string
              openOutgoingLinksInNewTab:
                type: boolean
              topicSearchEnabled:
                type: boolean
              hideSubCategories:
                type: boolean
              hideCategoryLastPost:
                type: boolean
              enableQuickReply:
                type: boolean
              iconBackgrounds:
                type: array
                items:
                  type: string
                  description: A valid CSS colour code
                  example: '#fff'
              emailPrompt:
                type: number
              useragent:
                type: object
                properties:
                  isYaBrowser:
                    type: boolean
                  isAuthoritative:
                    type: boolean
                  isMobile:
                    type: boolean
                  isMobileNative:
                    type: boolean
                  isTablet:
                    type: boolean
                  isiPad:
                    type: boolean
                  isiPod:
                    type: boolean
                  isiPhone:
                    type: boolean
                  isiPhoneNative:
                    type: boolean
                  isAndroid:
                    type: boolean
                  isAndroidNative:
                    type: boolean
                  isBlackberry:
                    type: boolean
                  isOpera:
                    type: boolean
                  isIE:
                    type: boolean
                  isEdge:
                    type: boolean
                  isIECompatibilityMode:
                    type: boolean
                  isSafari:
                    type: boolean
                  isFirefox:
                    type: boolean
                  isWebkit:
                    type: boolean
                  isChrome:
                    type: boolean
                  isKonqueror:
                    type: boolean
                  isOmniWeb:
                    type: boolean
                  isSeaMonkey:
                    type: boolean
                  isFlock:
                    type: boolean
                  isAmaya:
                    type: boolean
                  isPhantomJS:
                    type: boolean
                  isEpiphany:
                    type: boolean
                  isDesktop:
                    type: boolean
                  isWindows:
                    type: boolean
                  isLinux:
                    type: boolean
                  isLinux64:
                    type: boolean
                  isMac:
                    type: boolean
                  isChromeOS:
                    type: boolean
                  isBada:
                    type: boolean
                  isSamsung:
                    type: boolean
                  isRaspberry:
                    type: boolean
                  isBot:
                    type: boolean
                  isCurl:
                    type: boolean
                  isAndroidTablet:
                    type: boolean
                  isWinJs:
                    type: boolean
                  isKindleFire:
                    type: boolean
                  isSilk:
                    type: boolean
                  isCaptive:
                    type: boolean
                  isSmartTV:
                    type: boolean
                  isUC:
                    type: boolean
                  isFacebook:
                    type: boolean
                  isAlamoFire:
                    type: boolean
                  isElectron:
                    type: boolean
                  silkAccelerated:
                    type: boolean
                  browser:
                    type: string
                  version:
                    type: string
                  os:
                    type: string
                  platform:
                    type: string
                  geoIp:
                    type: object
                  source:
                    type: string
                  isWechat:
                    type: boolean
              composer-default:
                type: object
              fontawesome:
                type: object
                properties:
                  pro:
                    type: boolean
                  styles:
                    type: array
                    items:
                      type: string
                  version:
                    type: string
