name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Github Issues are for bug reports and feature requests only
        Please visit https://community.nodebb.org for other support
        Found a security exploit? Please email us at security@nodebb.org instead for immediate attention
        ### → DO NOT SUBMIT VULNERABILITIES TO THE PUBLIC BUG TRACKER ←
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    attributes:
      label: Community forum reference
      description: If this feature was already discussed on the Community Forum link it here
      placeholder: https://community.nodebb.org/topic/0/example-feature-request
  - type: markdown
    attributes:
      value: "**Thank you!**"
